### PR TITLE
Merge changes for v1.1

### PR DESCRIPTION
**Pull request by rmrao**
Merge develop into master for a v1.1 release.

### CODE REVIEW

**Review by DavidMChan — CHANGES_REQUESTED** [review]
This won't upload to pypi without the latest commit on the develop branch. We need to include that in the PR.

**Comment by rmrao** [comment]
Added the requested changes

**Review by DavidMChan — APPROVED** [review]

**Comment by DavidMChan** [comment]
I bumped the version number as well to 1.1 - This will help us keep things straight later. I really hope travis decides to build these things :)

**Comment by rmrao** [comment]
Yeah and I realized that I forgot to update the name to `rinokeras` from `rinokeras-nightly`

**Pull request merged**
